name: mercadofoto_app
description: "Marketplace con IA para publicación de productos desde imágenes"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Core app
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.2

  http: 0.13.6
  local_auth: ^2.3.0

  # Geolocalización
  geolocator: ^12.0.0

  # Mapa (OpenStreetMap, sin API key)
  flutter_map: ^4.0.0
  latlong2: ^0.8.2

  # Compartir / deep-links (WhatsApp, etc.)
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/banner_publicidad.jpg